const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
const source = fs.readFileSync('web/templates/settings.html', 'utf8');
const script = [...source.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].find(m => m[1].includes('function systemUpdate()'))[1];
let timers = new Map(), next = 0;
const ctx = { console, setTimeout(fn) { timers.set(++next, fn); return next; }, clearTimeout(id) { timers.delete(id); } };
vm.createContext(ctx); vm.runInContext(script, ctx);
const page = ctx.systemUpdate(); let refreshes = 0;
page.check = () => { refreshes++; };
page.applyStatus({status:'success', message:'Some packages remain', detail:'linux-image-amd64 → 6.12.111-1', remaining_count:1}, true);
assert.equal(page.ok, false);
assert.equal(page.remainingCount, 1);
assert.match(page.detail, /linux-image-amd64/);
assert.equal(page.msg, 'Some packages remain');
assert.equal(page.successTimer, null);
assert.equal(refreshes, 1);
page.applyStatus({status:'running', message:'Installing', remaining_count:0});
assert.equal(page.updating, true);
page.applyStatus({status:'success', message:'Completed', remaining_count:0});
assert.equal(page.remainingCount, 0);
assert.equal(page.ok, true);
assert.ok(page.successTimer);
page.applyStatus({status:'success', message:'Some packages remain', detail:'held-package', remaining_count:1});
assert.equal(page.successTimer, null, 'a previous success timer must not hide a pending warning');
console.log('Remaining update warnings persist, refresh the package list, and clear on a new successful update.');
